### ISSUE TITLE
feat: rely on mainnet prices for tokens 

### ISSUE THREAD

**Issue by thelostone-mc** [gitcoinco/grants-stack#1048]
### Description

Currently, the API package has 3 endpoints for updating information:
- round summary
- project summary 
- match summary 

We rely on coingecko to get USD rates but we have scenarios like fantom BUSD for which coingecko doesn't return conversion rates. The goal of this ticket is to figure out a means to always rely on the mainnet prices as the source of truth.

That way whether you are contributing BUSD on a fantom / optimism / ethereum mainnet round  -> we always fetch the ethereum mainnet conversion rate. (this is a possible solution)

**Comment by thelostone-mc** [comment]
Possible solution : 

Since we have a finite list of currency, we maintain a mapping of

`token symbol | eth address | fantom address | goerli address | mainnet address `

at our end. This way we have alternate addresses we can look up
This again will work as long as we control the list of addresses and eventually we can write up a script / use an existing service to update these mappings

**Comment by DanieleSalatti** [comment]
> @thelostone-mc I feel we should rely on mainnet prices only as a backup, because there could be a possibility where some tokens are only available on L2 but not on mainnet.

Optimism is probably a good example of this, the OP token exists only on L2.

**Comment by DanieleSalatti** [comment]
I'm working on #1051 

Any reason why we are not using the [Uniswap Pricing API](https://docs.uniswap.org/sdk/v2/guides/pricing)?

We can pick one stablecoin per chain and use that to fetch the pricing for non-stable stuff. This works as long as Uniswap exists on the chain.

Some chains are not going to have Uniswap, but imo we can assume there will be other exchanges we can use to get data from the chain itself. Fantom has [fUni](https://funi.exchange/#/swap/) which is a fork of Uniswap - the SDK might work there, or we can check the SDK code and directly call fUni on-chain.

(I'm wondering how this can work with other FIATs, where e.g. people in EU might want to show amounts in EUR instead of USD...thinking of this especially as a decentralised protocol that people might want to use in slightly different ways)

**Comment by DanieleSalatti** [comment]
Sushi on FTM does not have BUSD. All other use cases seem to be covered.
