### ISSUE TITLE
Manager: add more education throughout round setup flow explaining what Gitcoin Explorer is

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#1785]
**User Story:**
As a
I want to
So that

**Acceptance Criteria**
GIVEN
WHEN
THEN

**Product & Design Links:**
* We would want to add this copy to create and edit flow 

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by willsputra** [comment]
Since the public/private question shows up at the start of the flow, this would be a good place to introduce Gitcoin Explorer to users. wdyt? @michellema1208

clicking the Gitcoin Explorer link will open Explorer on a new tab
![image](https://github.com/gitcoinco/grants-stack/assets/19514207/9ecfd8c5-2e51-45e4-9696-13a2c88f4bb0)


Figma: https://www.figma.com/file/V113F2Pp5m2qDM5odXjfFu/Manager-S17?type=design&node-id=1822-42168&t=1wjtG9eIPKgT3xJV-4

**Comment by michellema1208** [comment]
@willsputra I love this! Also moving this for ready for Eng work :)
