### ISSUE TITLE
Data for cart research

### ISSUE THREAD

**Issue by meg-fsc** [gitcoinco/grants-stack#1792]
As a PM, I am doing research on our cart / checkout experience in Grants Stack. Outside of gas fees, this was the top theme of user feedback from the beta round. Adding data to this feedback will allow us to further quantify the impact of our current checkout experience and prioritize the right fixes + right effort devoted to fixes. 

Data asks are listed below -- please feel free to send over any questions or suggestions on them!

- Number of projects per donor: beta vs cGrants
- Relationship between lifetime donations & number of projects supported (do donors who support more projects have a sticker relationship with the platform?)
- Number of projects donated to correlated with overall donation size (did we miss out on $$ – can we draw a general pattern here irrespective of this round’s gas fees)
- Number and % of total projects hitting $1000 USD funding threshold (were our projects less successful because of this specific checkout hurdle)

**Comment by baokiddy** [comment]
- [ ] Number of projects per donor: beta vs cGrants
- [ ] Relationship between lifetime donations & number of projects supported (do donors who support more projects have a sticker relationship with the platform?)
- [ ] Number of projects donated to correlated with overall donation size (did we miss out on $$ – can we draw a general pattern here irrespective of this round’s gas fees)
- [ ] Number and % of total projects hitting $1000 USD funding threshold (were our projects less successful because of this specific checkout hurdle)
 
I'll add notes on these as I work on the data

**Comment by michellema1208** [comment]
hey @baokiddy - is this ticket something you're actively working on? Or is this complete?
