### ISSUE TITLE
upgrade to node 20 LTS

### ISSUE THREAD

**Issue by vacekj** [gitcoinco/grants-stack#1831]
Node 20 is the latest LTS version
Do this across all our repositories

- [x] Manager
- [x] Builder
- [x] Explorer

will be closed by #1848

**Comment by vacekj** [comment]
I answered this in a previous comment somewhere, but: 20 is the current version. 16, which is our current version, will be deprecated this October. Unless we have a specific reason why we need 16, IMO it's a good idea to keep up-to-date. One important thing to note is that we are only using node for jest and building here, so it's a very minor upgrade since it doesn't affect our bundles at all.

Let me know if we have any specific reasons to stay on 16, or if we want to do 18 since that's what most service providers like AWS and Vercel support. Also keep in mind this is not a hard requirement - builds will not fail if you have an older node verison, it will just print a warning.

**Comment by boudra** [comment]
@vacekj @gravityblast  I am happy to upgrade to a LTS version if we want to, I don't think upgrading is an issue, **technically**.

But I have some more higher level points that I really want to make:

- I would really love if we focused on stuff that makes a difference as DIRECTLY AS POSSIBLE to making our users happier, we have lots of bugs and other things to fix and improve, not sure how this moves the needle.
- I would appreciate if we can frame proposed changes like this: "We need to do X because of Z" and then we can see as a team, if Z is a problem we want to solve now, for example: "we need to upgrade to Node 18, because we need native BigInts". Upgrading node because AWS and Vercel do it, or because it's new are not a good enough reason.
- But whatever we decide, what we absolutely cannot do is sneak changes inside bigger PRs, this just adds chaos to the team makes changes harder to review, we can do better.

Also not sure where this task came from, I see it was created and moved to this board directly.

I really want to push us to work as a team, we've already talked about these points multiple times now.

**Comment by vacekj** [comment]
Understood, agree and I will keep your points in mind. 

The origin of this ticket is the allo general board where we were tracking tech debt items. 

I agree that this doesn't move the needle, I meant this as a quick change, didn't expect it to be so contentious. let's do 18 if you aren't opposed, in a separate branch from the viem branch.

**Comment by gravityblast** [comment]
one important thing is that the Allo contracts repo doesn't work with 18, it works only with 16 until we fix/change the hardware wallet lib we use. 
Also, in the same repo, you can't deploy to a local chain with 18, it works only with 16. 
So until we are able to upgrade Allo, we should keep grants stack with 16 to be able to use both Allo and Grants Stack easily without continuously switching node version during development.
