### ISSUE TITLE
Manager: if the round has already started, add more help text as to why I can no longer edit the round

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#1859]
### 6/20/23 Update: Backlogged from Round Edit Flow milestone

**User Story:**
As a PROGRAM MANAGER 
I want to know what parts of my round I can edit if my round has already started 
So that I know what fields I can still update 

**Acceptance Criteria**
GIVEN that the round has already started but has not ended 
WHEN I navigate to that round's Round Settings page 
THEN I can still click "Edit Round" 

GIVEN that I click "Edit Round" 
WHEN I look at the page 
THEN I see a purple alert with copy informing me what parts of my round I can still edit 
AND I no longer see the standard copy that reads "Once the round starts, you'll only be able to change the Round End Date." 

GIVEN that I am on the "Round & Application Period" tab 
WHEN I look at the page 
THEN I see that I can still edit the round end date 
AND all other fields are greyed out / readonly 

GIVEN that my round has ended 
WHEN I navigate to that round's Round Settings page 
THEN I see that the "Edit" button has been replaced with a disabled button that reads "Round has ended" 

**Product & Design Links:**
* [Figma](https://www.figma.com/file/V113F2Pp5m2qDM5odXjfFu/Manager-S17?type=design&node-id=2106-44799&t=F8D6sAMyXE5RcrsM-0#458016112)

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by willsputra** [comment]
@michellema1208 just tested this out! part of the confusion I think is because some of the inputs still appear editable even though they're not. so we need to make sure that all inputs except for Round End Date are greyed out



![Image](https://github.com/gitcoinco/grants-stack/assets/19514207/153da44e-563c-47d5-bada-d3beaf24c45e)



![Image](https://github.com/gitcoinco/grants-stack/assets/19514207/abf8b2d8-cefe-4756-a864-61020a7bec33)



![Image](https://github.com/gitcoinco/grants-stack/assets/19514207/ba58878e-6027-4b5f-84be-0e5e7fc71c96)

I'll also explore putting some info to make it more obvious!

sidenote: when testing, I also encountered a bug:
when the round has started, and I click Edit Round, then I click Cancel - I got to this weird state where the 'Edit Button' is fully disabled.


![Image](https://github.com/gitcoinco/grants-stack/assets/19514207/ffd73802-3fa6-4a8e-9a87-fb892e1bf20b)

**Comment by michellema1208** [comment]
@willsputra good catch! I'm tracking that bug here: https://github.com/gitcoinco/grants-stack/issues/1901
