### ISSUE TITLE
Manager: unable to edit round end date

### ISSUE THREAD

**Issue by meglister** [gitcoinco/grants-stack#2113]
**Overview**
I am unable to edit the round end date because of a gas estimation bug. This loom was taken on staging but I verified that the same behavior is happening in production.

**Steps To Reproduce**
1. Go to https://rmgitcoin.on.fleek.co/#/round/0xbd84a5c0affbcd4bf285ab20ebecae20f0a31f36?debug=true
2. Click on Round settings -> Dates -> Edit
3. Try to change the round date to LATER than the previous date

**Observed  behavior**
Loom: https://www.loom.com/share/d7fcdc91338347f38598377d5e1ba650

**Screenshots**
Console error: 
<img width="531" alt="Screenshot 2023-08-03 at 8 12 26 PM" src="https://github.com/gitcoinco/grants-stack/assets/72808678/d5df4d9f-129a-4108-89f9-a9a3389e6c24">

**Comment by vacekj** [comment]
@gitcoinco/grantsstack-product @gitcoinco/grantsstack-engineering there's a small issue here: in the contract, there's this check: 
```solidity
require(block.timestamp <= newApplicationsStartTime, "Round: Time has already passed");
```
which ensures that whenever the round/application start/end times are updated (it's all done using one function), the newApplicationsStartTime have to be in the future (higher than the current block timestamp, so technically could be like 5 minutes in the future).

I don't remember why this requirement was added, seems pretty arbitrary to me.

What this means is that once applications have started, we can't edit any of the other time values without also updating the applications start to "now + a few blocks".

This presents a challenge, because even if we updated the applications to start in a few minutes, it could still reject people who are just now submitting their application. We can try to minimize this downtime by increasing the gas and decreasing the delay, but it's a very inelegant solution, and it also tampers with the actual "applications started" date unnecessarily.

The short-term, front-end-only solution is to do exactly that.

The long-term, proper solution is to upgrade the contracts to remove this check.

Let me know your thoughts.

**Comment by bhargavaparoksham** [comment]
@vacekj 

Once application period has started ,applicationStartTime wouldn't get updated because its in the past. See below condition.

```solidity
if (
      applicationsStartTime >= block.timestamp &&
      newApplicationsStartTime != applicationsStartTime
    ) {
      emit ApplicationsStartTimeUpdated(applicationsStartTime, newApplicationsStartTime);
      applicationsStartTime = newApplicationsStartTime;
    }
```

So even if we set newApplicationsStartTime = "now + a few blocks", the applicationsStartTime state will not change isn't it?

**Comment by vacekj** [comment]
@bhargavaparoksham This is actually true - dunno why I missed it. So we can actually set the applicationsStartTime to anytime in the future, and the value won't actually get overwritten. Cool. Then I'll do that.
