### ISSUE TITLE
Builder: Logo not uploading correctly

### ISSUE THREAD

**Issue by jesuloluwao** [gitcoinco/grants-stack#2176]
The user tried to upload an image on builder but it only shows black. I attached the image below.
![Lume logomark](https://github.com/gitcoinco/grants-stack/assets/88308638/60d85b26-2bd9-427c-94b5-31410c555ef8)
 
I think this is because the image is without a background. Builder is not rendering it properly. Loom recording here https://www.loom.com/share/bc8b0dc80330404db69045bebc8b85fe?sid=348b58dc-47d8-4fd2-9c6a-edcdf4023a52

> I am trying to upload a new logo under "Project Logo", however, the logo goes completely black. I am exporting from a SVG with black text, and making no transparency. from a dev pov, it seems to be trying to show it as a JPEG format.

**Link:** [Conversation with business@derrickhammer.com](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/63920)

**Customer:** [business@derrickhammer.com](https://app.intercom.com/a/apps/xaafeyri/users/64d3671bbea26633889cfe8f/all-conversations)
**Customer ID:** 53b3bf26-cad7-4f80-8709-98d47f19b6c1
___
Intercom Operator will send a note to [this conversation](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/63920) when this issue is closed.

**Comment by vacekj** [comment]
Confirming that uploading a PNG image with transparency defaults the background to black. This means that black logos without a background will blend in. This is because we save the png with transparency as a jpeg (likely to conserve data) in [ImageInput](https://github.com/gitcoinco/grants-stack/blob/630571acd4ec6dbb32e4650aff8468213eeafb17/packages/builder/src/components/base/ImageInput.tsx#L205). 

The choice here would be to either
1. not re-encode the images as jpeg and leave them as-is, which would solve this issue but can present issues down the line because images aren't "standardized"
2. don't change code, but let users know that the background will be filled black if they upload a transparent image.

@gitcoinco/grantsstack-product @gitcoinco/grantsstack-engineering @gitcoinco/grantsstack-design let me know your thoughts

**Comment by melissa-neira** [comment]
@vacekj I think the simplest solution here is the second option you have there, to just inform the user about that limitation. it'd be really cool if we could implement image transparency in the future through because it seems to be the standard in most social media sites. I defer to @michellema1208 for the final decision!

**Comment by michellema1208** [comment]
Agreed with adding copy for the user, maybe something like "Note: If the image you are uploading is black, please include a non-transparent background in order for the image to render correctly" -- feel free to adjust! 

Thanks both @melissa-neira @vacekj !
