### ISSUE TITLE
[GG18] Manager: GCC team unable to finalize results

### ISSUE THREAD

**Issue by jesuloluwao** [gitcoinco/grants-stack#2364]
**Problem**: The Round Manager for the Global Chinese Community Round in GG18 is getting an error when they try to finalize results. Their round contract is fully funded, and the Round Manager confirmed that they have enough ETH on OP to cover gas. 

* Round Contract: 0x30c381033aa2830ceb0aa372c2e4d28f004b3db9 
* Manager debug view: https://manager.gitcoin.co/#/round/0x30c381033aa2830ceb0aa372c2e4d28f004b3db9?debug=true

Screenshots: 

Before clicking "Finalize Results": 

![Image](https://github.com/gitcoinco/grants-stack/assets/26017180/84c842b7-2210-4456-a3a9-c9b4e50b5c58)

After clicking "Finalize Results": 

![Image](https://github.com/gitcoinco/grants-stack/assets/26017180/8eb1e45e-db62-4ffe-a23b-bfa92d633574)

**Comment by jesuloluwao** [comment]
I'll provide more information on this round as soon as I get a response

**Comment by michellema1208** [comment]
### Archives (moving this out of the main ticket to keep it clean) 

**9/21/23 Update:** 
From GCC Round Manager: "After we upload the csv. file, successfully "upload and revise" and trying to finalize the results, it shows an error message. The error is happening at the first step - uploading to IPFS.

* Round Contract: 0x30c381033aa2830ceb0aa372c2e4d28f004b3db9 
* Manager debug view: https://manager.gitcoin.co/#/round/0x30c381033aa2830ceb0aa372c2e4d28f004b3db9?debug=true
* Override CSV below

[override.csv](https://github.com/gitcoinco/grants-stack/files/12693262/override.csv)

Console error: 

![Image](https://github.com/gitcoinco/grants-stack/assets/26017180/efeea6c0-c394-483d-9670-4416a0f6bbd0)

![Image](https://github.com/gitcoinco/grants-stack/assets/26017180/c7ae1491-fa7d-4c27-b6a3-a5a9c4a47a30)

**Original Context**
The round operator for our china featured round reported an issue with uploading a revised coefficients file. After trying to upload a file it does not appear the file was uploaded successfully. The file select screen pops open and he is able to select a file. But afterward the color of the 'Upload and revise' button remains gray. Thank you for taking a look at this! Here is the relevant conversation:

Them: " sure. so in the guide, it says we can upload the .csv file to override current matching co-efficient, however on my round operator UI, this button is grey and I cannot upload anything (it only pops-up the file select page but you cannot actually upload anything)"

**Link:** [Conversation with umar](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/65313)

**Customer:** [umar](https://app.intercom.com/a/apps/xaafeyri/users/64ac0017471c413a5277da76/all-conversations)
**Customer ID:** 94e7cfc1-07b0-47fc-87ec-ddb285053cc8
___
Intercom Operator will send a note to [this conversation](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/65313) when this issue is closed.

**Comment by bard** [comment]
Perhaps an internal error on Optimism side? Related: https://github.com/ethereum-optimism/optimism/issues/2618

**Comment by boudra** [comment]
Looks like this issue is specific to the optimism.io RPC, while they get this sorted, could we ask the round operator to configure another RPC in Metamask? they could do it here: https://www.alchemy.com/chain-connect/chain/optimism

Just tried the 1RPC and it worked well for me.

**Comment by michellema1208** [comment]
@gravityblast @boudra - I believe I successfully added 1RPC for Optimism, but when I go to the GCC round under debug view and click "Finalize Results", I'm still running into an error (screenshot below). Let me know if I maybe missed a step! 

Link: https://manager.gitcoin.co/#/round/0x30c381033aa2830ceb0aa372c2e4d28f004b3db9?debug=true 

<img width="1428" alt="Screen Shot 2023-10-03 at 11 44 37 AM" src="https://github.com/gitcoinco/grants-stack/assets/26017180/0a23d8e9-c165-429f-bf61-e2efa82332a5">

<img width="1437" alt="Screen Shot 2023-10-03 at 11 45 05 AM" src="https://github.com/gitcoinco/grants-stack/assets/26017180/a61b3b5f-b328-4cde-9421-6da7588c25e2">

**Comment by michellema1208** [comment]
@boudra - oh gotcha - I thought I would be able to finalize results but just have the transaction rejected in the end. Will report back to GCC round team to have them try it out instead!

**Comment by gravityblast** [comment]
@michellema1208  your error is normal cause you can't finalize the round since your are not a round operator, and the gas estimation fails at the authentication step. 
@jesuloluwao we might try with a round operator to see if it works
