### ISSUE TITLE
Explorer: add sorting functionality to the round page 

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#2379]
**User Story:**
As a donor 
I want to easily discover projects on Grants Stack 
So that I can easily find new projects to support 

**Acceptance Criteria** 
GIVEN that I am on a round page 
WHEN I click on "Sort by" 
THEN I see I can sort by the following: 

- Newest to Oldest (sort by project creation date) 
- Oldest to Newest (sort by project creation date) 
- Donation amount - High to Low (total amount of donations received by a project in the round so far) 
- Donation amount - Low to High 
- Contributor count - High to Low (# of unique contributors a project has) 
- Contributor count - Low to High 

**Product & Design Links:**
* [Figma](https://www.figma.com/file/1uxgU2jb0yyN11SUgxARmF/Explorer-S19?type=design&node-id=300-14464&mode=design&t=os8gMWwBouzyFg6y-0)
* [Sample staging environment to see existing homepage](https://explorer-staging-git-bug-2394-grants-stack.vercel.app/#/)

**Tech Details:**

**Open Questions:**
* Q: Will sorting by "donation amount" and/or "contributor count" give any projects an unfair advantage? 
* > A: Maybe, but we've heard from user feedback that these sorts would be useful for donors to vet project legitimacy
* Are there any filters we should include for projects at the round page level? 
* > A: No, we can scope out filters for MVP

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by michellema1208** [comment]
@melissa-neira curious for your thoughts on both of the above open questions!

**Comment by melissa-neira** [comment]
@michellema1208 
1. good question - it could definitely introduce _some_ bias but not significantly. in a previous comment I made, I mentioned that in early research, users said that they would like to use these sorting options in order to vet a project's legitimacy. I believe we also had something similar in cgrants, so it would be nice to bring back this feature. a lot of our users used it.

2. I don't think so! I was just looking at the design, and I think that sorting options would suffice.

**Comment by michellema1208** [comment]
@melissa-neira got it, this is super helpful context to know! Let's keep it, and we'll scope out filtering options for now :)
