### ISSUE TITLE
Explorer: project search not returning exact results

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#2590]
### What was the URL where the error occurred?

https://explorer.gitcoin.co/#/projects?q=pledgepost

### What happened?

Loom: https://www.loom.com/share/e4944bd07c8143e7a7b8589ec840492a 

When searching for a project that exists, the project is not returned as a result 

### What should have happened instead?

The search results should yield the exact matches at the top of results. 

### Steps to Reproduce

1. Go to https://explorer.gitcoin.co/#/projects?q=pledgepost
2. See that "PledgePost" the project is not returned at all 

### What browser(s) are you seeing the problem on?

Chrome

### What chain(s) did the error occur on?

All

**Comment by bard** [comment]
An anomaly detection was in place that guarded against reloading the dataset if an updated dataset was smaller then the existing one. Relaxed this since, with applications now filtered by approval status, the dataset can shrink. Fixed in https://github.com/gitcoinco/grants-stack-search/commit/0b9f5ee32e02e2a22e65f7110bc4cf7a1b1ec4e6.

**Comment by gravityblast** [comment]
thank you @bard
