### ISSUE TITLE
chore: Investigate recurring missing donations from Donation History page

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#2936]
**Overview**
Prioritize investigation of recurring missing donations from Donation History page. Context: https://discord.com/channels/562828676480237578/1202639932636663858 

**Details**

- [ ] What's the root cause? 
- [ ] How can we detect when contributions are missing / Indexer for certain chain(s) are down, so that we're not reliant on manual reporting (i.e. the support team)?

**Comment by boudra** [comment]
There's no single root cause here to fix and get rid of the issue, this is a user facing issue that has many causes, at the moment we've been fixing each one as they come so they shouldn't happen again.

I am not sure that we can detect missing votes with another process as that would require building another sort of indexer, and who's going to test that one?

I suggest the best way forward is to do some manual checking using a trusted data source like Dune.

**Comment by michellema1208** [comment]
Closing as resolved
