### ISSUE TITLE
[SPIKE] investigate changes to move donation code to Allo V1

### ISSUE THREAD

**Issue by gravityblast** [gitcoinco/grants-stack#2963]
**Overview**
Investigate changes needed to be able to start with https://github.com/gitcoinco/grants-stack/issues/2817
and https://github.com/gitcoinco/grants-stack/issues/2938

**Details**
Say more

**Comment by vacekj** [comment]
Results of the spike: #2817 is strightforward to implement, and it involes moving all of the functions from `voting.ts` to the data-layer. `checkoutStore` should remain largery unchanged.

#2938 will add another method to donate instead of the v1 MRC method, and dynamically switch based on the allo version.
