### ISSUE TITLE
GE Project Cards: Pull in contributor stats

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-stack#770]
**User Story:**
As a user
I want to see how much funding a project has received
So that I can have an informed browsing experience

As a user
I want to see how many users have contributed to a project in a round
So that I can have an informed browsing experience

**Acceptance Criteria**
- [ ] Amount of funding a project has received thus far in a round (denominated in USD$)
- [ ] Number of contributors a project has thus far in a round

**Product & Design Links:**
[Figma](https://www.figma.com/file/cgsZMTG71f2Hf89J38simK/Explorer-S17?node-id=125-4439&t=6F16ax5mG45gexIe-4)

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by thelostone-mc** [comment]
This is not merged @bhargavaparoksham !
You should be able to fetch this information via the fetch-project-stats endpoint

**Comment by thelostone-mc** [comment]
Blocked by #836

**Comment by thelostone-mc** [comment]
This is blocked for the following reason : 

- Currently the round explorer page does not have pagination implemented. This means if a round has 40 projects -> since we load this information all at once in the frontend -> It won't scale and the fetch stats endpoint will take 10+ seconds to load 
- Each time this page is loaded -> we make a call to coingecko for the USD price -> as the number of projects increase -> we make more calls when we attempt to load the page -> causing coingecko to rate limit us 


How can we solve this ?

- Implement pagination, so that it eases the load on the server and queries are fast 
- Implement caching/storing the conversion rate into our DB making the queries faster

**Comment by nfrgosselin** [comment]
Load 20 per page — @melissa-neira to put together design

**Comment by melissa-neira** [comment]
@nfrgosselin @thelostone-mc updated with links to pagination design

**Comment by melissa-neira** [comment]
@thelostone-mc is this still blocked?

**Comment by bhargavaparoksham** [comment]
This is blocked until pagination is implemented in the frontend & bulk project - contributor stats endpoint is implemented in the api.

**Comment by nfrgosselin** [comment]
Zombie ticket — this is complete
